import './globals.css'

import { Footer, Header, MobileNav } from '@beborn/components/layout'
import ReactQueryProviders from '@beborn/shared/providers/QueryProvider'
import { SpeedInsights } from '@vercel/speed-insights/next'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='ko'>
      <body className='bg-white'>
        <Header />
        <main className='mx-auto max-w-7xl pb-20 lg:pb-0'>
          <ReactQueryProviders>{children}</ReactQueryProviders>
        </main>
        <Footer />
        <MobileNav />
        <SpeedInsights />
      </body>
    </html>
  )
}
