import './globals.css'

import { Footer, Header } from '@beborn/components/Layout'
import ReactQueryProviders from '@beborn/shared/providers/QueryProvider'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='ko'>
      <body>
        <Header />
        <div className='bg-white'>
          <main className='mx-auto max-w-7xl'>
            <ReactQueryProviders>{children}</ReactQueryProviders>
          </main>
          <Footer />
        </div>
      </body>
    </html>
  )
}
